# Generated by Django 5.2.13 on 2026-04-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('min_subject_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'admission_condition',
            },
        ),
        migrations.CreateModel(
            name='CombinationSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=3, default=1, max_digits=5)),
                ('score_type', models.CharField(choices=[('HOCBA', 'Học bạ'), ('THPT', 'Thi THPT'), ('DGNL', 'Đánh giá năng lực'), ('CB', 'Chuyên biệt')], default='THPT', max_length=10)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'combination_subject',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CutoffScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('cutoff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('round', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'cutoff_score',
            },
        ),
        migrations.CreateModel(
            name='CutoffScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_combination_id', models.IntegerField()),
                ('cutoff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('round', models.PositiveSmallIntegerField()),
                ('set_by_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cutoff_score_log',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quota', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='MajorCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('min_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dgnl_offset', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'major_combination',
            },
        ),
        migrations.CreateModel(
            name='MajorCombinationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.CharField(max_length=10)),
                ('subject_combination_id', models.CharField(max_length=20)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dgnl_offset', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_primary', models.BooleanField()),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'major_combination_log',
            },
        ),
        migrations.CreateModel(
            name='MajorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quota', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'major_log',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectCombination',
            fields=[
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'subject_combination',
            },
        ),
        migrations.CreateModel(
            name='SubjectCombinationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subject_combination_log',
            },
        ),
        migrations.CreateModel(
            name='SubjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subject_log',
            },
        ),
        migrations.CreateModel(
            name='AdmissionConditionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_combination_id', models.IntegerField()),
                ('subject_id', models.CharField(blank=True, max_length=10, null=True)),
                ('min_subject_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('admission_condition', models.ForeignKey(db_column='admission_condition_id', on_delete=django.db.models.deletion.CASCADE, to='programs.admissioncondition')),
            ],
            options={
                'db_table': 'admission_condition_log',
            },
        ),
        migrations.CreateModel(
            name='CombinationSubjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_combination_id', models.CharField(max_length=20)),
                ('subject_id', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('score_type', models.CharField(choices=[('HOCBA', 'Học bạ'), ('THPT', 'Thi THPT'), ('DGNL', 'Đánh giá năng lực'), ('CB', 'Chuyên biệt')], max_length=10)),
                ('position', models.PositiveSmallIntegerField()),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('combination_subject', models.ForeignKey(db_column='combination_subject_id', on_delete=django.db.models.deletion.CASCADE, to='programs.combinationsubject')),
            ],
            options={
                'db_table': 'combination_subject_log',
            },
        ),
    ]
