# Generated by Django 5.2.13 on 2026-04-26 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoffscore',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutoffs_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cutoffscorelog',
            name='cutoff_score',
            field=models.ForeignKey(db_column='cutoff_score_id', on_delete=django.db.models.deletion.CASCADE, to='programs.cutoffscore'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['id'], name='major_id_a82e38_idx'),
        ),
        migrations.AddField(
            model_name='majorcombination',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='programs.major'),
        ),
        migrations.AddField(
            model_name='cutoffscore',
            name='major_combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='programs.majorcombination'),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='major_combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='programs.majorcombination'),
        ),
        migrations.AddField(
            model_name='majorcombinationlog',
            name='major_combination',
            field=models.ForeignKey(db_column='major_combination_id', on_delete=django.db.models.deletion.CASCADE, to='programs.majorcombination'),
        ),
        migrations.AddField(
            model_name='majorlog',
            name='major',
            field=models.ForeignKey(db_column='major_id', on_delete=django.db.models.deletion.CASCADE, to='programs.major'),
        ),
        migrations.AddField(
            model_name='combinationsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combination_entries', to='programs.subject'),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='programs.subject'),
        ),
        migrations.AddField(
            model_name='majorcombination',
            name='subject_combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='major_combinations', to='programs.subjectcombination'),
        ),
        migrations.AddField(
            model_name='combinationsubject',
            name='subject_combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='programs.subjectcombination'),
        ),
        migrations.AddField(
            model_name='subjectcombinationlog',
            name='subject_combination',
            field=models.ForeignKey(db_column='subject_combination_id', on_delete=django.db.models.deletion.CASCADE, to='programs.subjectcombination'),
        ),
        migrations.AddField(
            model_name='subjectlog',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='programs.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='cutoffscore',
            unique_together={('major_combination', 'round')},
        ),
        migrations.AddIndex(
            model_name='majorcombination',
            index=models.Index(fields=['major'], name='major_combi_major_i_0434b9_idx'),
        ),
        migrations.AddIndex(
            model_name='majorcombination',
            index=models.Index(fields=['subject_combination'], name='major_combi_subject_3a7890_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='majorcombination',
            unique_together={('major', 'subject_combination')},
        ),
        migrations.AddIndex(
            model_name='combinationsubject',
            index=models.Index(fields=['subject_combination'], name='combination_subject_8e6d43_idx'),
        ),
        migrations.AddIndex(
            model_name='combinationsubject',
            index=models.Index(fields=['subject'], name='combination_subject_164ebe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='combinationsubject',
            unique_together={('subject_combination', 'subject')},
        ),
    ]
