# Generated by Django 5.2.13 on 2026-04-28 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationsubjectlog',
            name='combination_subject',
            field=models.ForeignKey(blank=True, db_column='combination_subject_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.combinationsubject'),
        ),
        migrations.AlterField(
            model_name='subjectcombinationlog',
            name='subject_combination',
            field=models.ForeignKey(blank=True, db_column='subject_combination_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.subjectcombination'),
        ),
        migrations.AlterField(
            model_name='subjectlog',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.subject'),
        ),
    ]
