# Generated by Django 5.2.13 on 2026-04-28 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_combinationsubjectlog_combination_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionconditionlog',
            name='admission_condition',
            field=models.ForeignKey(blank=True, db_column='admission_condition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.admissioncondition'),
        ),
        migrations.AlterField(
            model_name='cutoffscorelog',
            name='cutoff_score',
            field=models.ForeignKey(blank=True, db_column='cutoff_score_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.cutoffscore'),
        ),
        migrations.AlterField(
            model_name='majorcombinationlog',
            name='major_combination',
            field=models.ForeignKey(blank=True, db_column='major_combination_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.majorcombination'),
        ),
        migrations.AlterField(
            model_name='majorlog',
            name='major',
            field=models.ForeignKey(blank=True, db_column='major_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.major'),
        ),
    ]
