# Generated by Django 5.2.13 on 2026-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_rename_score_offset_and_condition_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='majorcombinationlog',
            name='major_id',
            field=models.CharField(max_length=50),
        ),
    ]
