# Generated by Django 5.2.13 on 2026-04-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('admitted', 'Trúng tuyển'), ('rejected', 'Không đậu'), ('pending', 'Chờ xét')], default='pending', max_length=10)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('round', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admission_result',
            },
        ),
        migrations.CreateModel(
            name='Aspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('computed_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'aspiration',
            },
        ),
        migrations.CreateModel(
            name='AspirationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.UUIDField()),
                ('major_combination_id', models.IntegerField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('computed_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aspiration_log',
            },
        ),
        migrations.CreateModel(
            name='PassedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'passed_candidate',
            },
        ),
        migrations.CreateModel(
            name='PassedCandidateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.UUIDField()),
                ('major_combination_id', models.IntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'passed_candidate_log',
            },
        ),
        migrations.CreateModel(
            name='AdmissionResultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspiration_id', models.IntegerField()),
                ('status', models.CharField(choices=[('admitted', 'Trúng tuyển'), ('rejected', 'Không đậu'), ('pending', 'Chờ xét')], max_length=10)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('round', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('admission_result', models.ForeignKey(db_column='admission_result_id', on_delete=django.db.models.deletion.CASCADE, to='aspirations.admissionresult')),
            ],
            options={
                'db_table': 'admission_result_log',
            },
        ),
    ]
