# Generated by Django 5.2.13 on 2026-04-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aspirations', '0002_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspiration',
            name='major_combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aspirations', to='programs.majorcombination'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='aspiration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='aspirations.aspiration'),
        ),
        migrations.AddField(
            model_name='aspirationlog',
            name='aspiration',
            field=models.ForeignKey(db_column='aspiration_id', on_delete=django.db.models.deletion.CASCADE, to='aspirations.aspiration'),
        ),
    ]
