# Generated by Django 5.2.13 on 2026-04-26 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aspirations', '0003_initial'),
        ('candidates', '0003_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passedcandidate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passedcandidate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_entries', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='passedcandidate',
            name='major_combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_candidates', to='programs.majorcombination'),
        ),
        migrations.AddField(
            model_name='passedcandidatelog',
            name='passed_candidate',
            field=models.ForeignKey(db_column='passed_candidate_id', on_delete=django.db.models.deletion.CASCADE, to='aspirations.passedcandidate'),
        ),
        migrations.AddIndex(
            model_name='aspiration',
            index=models.Index(fields=['candidate'], name='aspiration_candida_e68321_idx'),
        ),
        migrations.AddIndex(
            model_name='aspiration',
            index=models.Index(fields=['major_combination', 'computed_score'], name='aspiration_major_c_37b3b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='aspiration',
            constraint=models.UniqueConstraint(fields=('candidate', 'rank'), name='uq_aspiration_rank'),
        ),
        migrations.AddConstraint(
            model_name='aspiration',
            constraint=models.UniqueConstraint(fields=('candidate', 'major_combination'), name='uq_aspiration_major_combination'),
        ),
        migrations.AddIndex(
            model_name='admissionresult',
            index=models.Index(fields=['status', 'round'], name='admission_r_status_804aaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='passedcandidate',
            constraint=models.UniqueConstraint(fields=('candidate', 'major_combination'), name='uq_passed_candidate'),
        ),
    ]
