# Generated by Django 5.2.13 on 2026-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirations', '0006_aspiration_major_and_exclusions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirationlog',
            name='major_id',
            field=models.CharField(max_length=50),
        ),
    ]
