# Generated by Django 5.2.13 on 2026-04-26 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Chờ'), ('processing', 'Đang xử lý'), ('done', 'Hoàn thành'), ('failed', 'Lỗi')], default='pending', max_length=15)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_batch',
            },
        ),
        migrations.CreateModel(
            name='ImportBatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('imported_by_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ'), ('processing', 'Đang xử lý'), ('done', 'Hoàn thành'), ('failed', 'Lỗi')], max_length=15)),
                ('row_count', models.PositiveIntegerField()),
                ('created_count', models.PositiveIntegerField()),
                ('updated_count', models.PositiveIntegerField()),
                ('error_count', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'import_batch_log',
            },
        ),
    ]
