# Generated by Django 5.2.13 on 2026-04-26 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatchlog',
            name='import_batch',
            field=models.ForeignKey(db_column='import_batch_id', on_delete=django.db.models.deletion.CASCADE, to='imports.importbatch'),
        ),
    ]
