# Generated by Django 5.2.13 on 2026-04-28 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatchlog',
            name='import_batch',
            field=models.ForeignKey(blank=True, db_column='import_batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='imports.importbatch'),
        ),
    ]
