# Generated by Django 5.2.13 on 2026-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PercentileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('percentile', models.PositiveSmallIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('round', models.PositiveSmallIntegerField(default=1)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'percentile_snapshot',
            },
        ),
        migrations.CreateModel(
            name='PercentileSnapshotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_combination_id', models.IntegerField()),
                ('percentile', models.PositiveSmallIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('round', models.PositiveSmallIntegerField()),
                ('computed_at', models.DateTimeField()),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'percentile_snapshot_log',
            },
        ),
    ]
