# Generated by Django 5.2.13 on 2026-04-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentilesnapshot',
            name='major_combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentile_snapshots', to='programs.majorcombination'),
        ),
        migrations.AddField(
            model_name='percentilesnapshotlog',
            name='percentile_snapshot',
            field=models.ForeignKey(db_column='percentile_snapshot_id', on_delete=django.db.models.deletion.CASCADE, to='analytics.percentilesnapshot'),
        ),
        migrations.AddIndex(
            model_name='percentilesnapshot',
            index=models.Index(fields=['major_combination', 'round'], name='percentile__major_c_e52fc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='percentilesnapshot',
            constraint=models.UniqueConstraint(fields=('major_combination', 'percentile', 'round'), name='uq_percentile_snapshot'),
        ),
    ]
