# Generated by Django 5.2.13 on 2026-04-26 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cccd', models.CharField(max_length=12, unique=True)),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('academic_level', models.CharField(blank=True, max_length=1, null=True)),
                ('graduation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='CandidateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccd', models.CharField(max_length=12)),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('academic_level', models.CharField(blank=True, max_length=1, null=True)),
                ('graduation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('import_batch_id', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'candidate_log',
            },
        ),
        migrations.CreateModel(
            name='RegionPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('region_code', models.CharField(max_length=5)),
                ('special_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bonus_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'db_table': 'region_priority',
            },
        ),
        migrations.CreateModel(
            name='RegionPriorityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.UUIDField()),
                ('region_code', models.CharField(max_length=5)),
                ('special_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bonus_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'region_priority_log',
            },
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('score_type', models.CharField(choices=[('HOCBA', 'Học bạ'), ('THPT', 'Thi THPT'), ('DGNL', 'Đánh giá năng lực'), ('CB', 'Chuyên biệt')], max_length=10)),
            ],
            options={
                'db_table': 'score_board',
            },
        ),
        migrations.CreateModel(
            name='ScoreBoardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.UUIDField()),
                ('score_type', models.CharField(choices=[('HOCBA', 'Học bạ'), ('THPT', 'Thi THPT'), ('DGNL', 'Đánh giá năng lực'), ('CB', 'Chuyên biệt')], max_length=10)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'score_board_log',
            },
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'subject_score',
            },
        ),
        migrations.CreateModel(
            name='SubjectScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_board_id', models.IntegerField()),
                ('subject_id', models.CharField(max_length=10)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subject_score_log',
            },
        ),
    ]
