# Generated by Django 5.2.13 on 2026-04-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='candidatelog',
            name='candidate',
            field=models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='regionpriority',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='region_priority', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='regionprioritylog',
            name='region_priority',
            field=models.ForeignKey(db_column='region_priority_id', on_delete=django.db.models.deletion.CASCADE, to='candidates.regionpriority'),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_boards', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='scoreboardlog',
            name='score_board',
            field=models.ForeignKey(db_column='score_board_id', on_delete=django.db.models.deletion.CASCADE, to='candidates.scoreboard'),
        ),
        migrations.AddField(
            model_name='subjectscore',
            name='score_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='candidates.scoreboard'),
        ),
    ]
