# Generated by Django 5.2.13 on 2026-04-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectscore',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='programs.subject'),
        ),
        migrations.AddField(
            model_name='subjectscorelog',
            name='subject_score',
            field=models.ForeignKey(db_column='subject_score_id', on_delete=django.db.models.deletion.CASCADE, to='candidates.subjectscore'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['cccd'], name='candidate_cccd_b687ce_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['ticket_number'], name='candidate_ticket__f7e64f_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreboard',
            index=models.Index(fields=['candidate'], name='score_board_candida_aab4bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scoreboard',
            unique_together={('candidate', 'score_type')},
        ),
        migrations.AddIndex(
            model_name='subjectscore',
            index=models.Index(fields=['score_board', 'subject'], name='subject_sco_score_b_9411f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectscore',
            unique_together={('score_board', 'subject')},
        ),
    ]
