# Generated by Django 5.2.13 on 2026-04-26 15:12

import django.db.models.deletion
from django.db import migrations, models


def seed_regions_from_existing_priorities(apps, schema_editor):
    # Existing priorities were stored as free-text KV codes before Region became master data.
    Region = apps.get_model('candidates', 'Region')
    RegionPriority = apps.get_model('candidates', 'RegionPriority')
    existing_codes = (
        RegionPriority.objects.exclude(region_code__isnull=True)
        .exclude(region_code='')
        .values_list('region_code', flat=True)
        .distinct()
    )
    for code in existing_codes:
        Region.objects.get_or_create(code=code, defaults={'bonus_score': 0})


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_ticket_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bonus_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.AlterField(
            model_name='regionpriority',
            name='region_code',
            field=models.CharField(max_length=20, db_index=True),
        ),
        migrations.RunPython(
            seed_regions_from_existing_priorities,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            # Rename only in Django state; the physical DB column remains region_code.
            state_operations=[
                migrations.RenameField(
                    model_name='regionpriority',
                    old_name='region_code',
                    new_name='region',
                ),
                migrations.AlterField(
                    model_name='regionpriority',
                    name='region',
                    field=models.CharField(max_length=20, db_column='region_code', db_index=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='regionpriority',
            name='region',
            field=models.ForeignKey(db_column='region_code', on_delete=django.db.models.deletion.PROTECT, related_name='candidate_priorities', to='candidates.region'),
        ),
        migrations.CreateModel(
            name='RegionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('bonus_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(db_column='region_code', on_delete=django.db.models.deletion.CASCADE, to='candidates.region')),
            ],
            options={
                'db_table': 'region_log',
            },
        ),
    ]
