# Generated by Django 5.2.13 on 2026-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_region_alter_regionpriority_region_code_regionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionprioritylog',
            name='region_code',
            field=models.CharField(max_length=20),
        ),
    ]
