# Generated by Django 5.2.13 on 2026-04-28 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_regionprioritylog_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatelog',
            name='candidate',
            field=models.ForeignKey(blank=True, db_column='candidate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='regionlog',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.region'),
        ),
        migrations.AlterField(
            model_name='regionprioritylog',
            name='region_priority',
            field=models.ForeignKey(blank=True, db_column='region_priority_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.regionpriority'),
        ),
        migrations.AlterField(
            model_name='scoreboardlog',
            name='score_board',
            field=models.ForeignKey(blank=True, db_column='score_board_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.scoreboard'),
        ),
        migrations.AlterField(
            model_name='subjectscorelog',
            name='subject_score',
            field=models.ForeignKey(blank=True, db_column='subject_score_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.subjectscore'),
        ),
    ]
