# Generated by Django 5.2.13 on 2026-04-28 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_alter_candidatelog_candidate_alter_regionlog_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityObject',
            fields=[
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], default='create', max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bonus_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'priority_object',
            },
        ),
        migrations.RemoveField(
            model_name='regionpriority',
            name='special_code',
        ),
        migrations.AddField(
            model_name='regionpriority',
            name='priority_object',
            field=models.ForeignKey(blank=True, db_column='special_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_priorities', to='candidates.priorityobject'),
        ),
        migrations.CreateModel(
            name='PriorityObjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('bonus_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], max_length=10)),
                ('field_changed', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('priority_object', models.ForeignKey(blank=True, db_column='priority_object_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.priorityobject')),
            ],
            options={
                'db_table': 'priority_object_log',
            },
        ),
    ]
